using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Net;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using System.Windows;
using System.ComponentModel;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;
using Microsoft.Win32;
using Newtonsoft.Json;

namespace mydrive_client
{
    public enum TransferType { Download, Upload };
    // Error types for transfers
    public enum TransferStatus { CHUNK_TRANSFER_SUCCESS, FILE_TRANSFER_COMPLETE, FILE_ID_NOT_EXIST, SEVRER_NOTREACHABLE, INVALID_ERROR };

    /* ServerFileInfo - This class is used to hold information about the files server is hosting
     */
    public class ServerFileInfo
    {
        // Unique file id generated by server, used for all transactions
        public string file_id { get; set; }
        // Name of the file
        public string file_name { get; set; }
        // Total file size
        public long file_size { get; set; }
        // Used to deserializing server response. Status of the response
        public string error { get; set; }
    }

    /* FileTransfer - Class to hold information about upload/download
     */
    public class FileTransfer : INotifyPropertyChanged
    {
        // Unique file id generated by server, used for all transactions
        public string file_id { get; set; }
        // Local file path
        public string file_localpath { get; set; }
        // Upload/Download
        public TransferType transfer_type { get; set; }
        // Total bytes transferred. Used for retransmission
        public long bytes_transfered { get; set; }
        // Total file size
        public long total_size { get; set; }

        // Used for data binding of the progress bar.
        private int transfer_progress_;
        public int TransferProgress
        {
            get
            {
                return transfer_progress_;
            }
            set
            {
                transfer_progress_ = value;
                // Notify the control to update the value
                NotifyPropertyChanged("TransferProgress");
            }
        }

        // Used for data binding of the transfer message.
        private string transfer_message_;
        public string TransferMessage
        {
            get
            {
                return transfer_message_;
            }
            set
            {

                transfer_message_ = value;
                // Notify the control to update the value
                NotifyPropertyChanged("TransferMessage");
            }
        }

        public event PropertyChangedEventHandler PropertyChanged;
        private void NotifyPropertyChanged(String propertyName)
        {
            PropertyChangedEventHandler handler = PropertyChanged;
            if (null != handler)
            {
                handler(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /* WebResult - Used to receiv error message from web server
     */
    public class WebResult
    {
        public string error { get; set; }
    }

    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        // Base URL
        public static string BASE_URL = "http://localhost:5000";
        // URL to get server file list
        public static string GET_FILE_LIST_URL = BASE_URL + "/mydrive/list";
        // URL to get information about a pending file transfer
        public static string GET_PENDING_FILEINFO_URL = BASE_URL + "/mydrive/pendingfileinfo";
        // URL to initiate a file upload
        public static string INIT_UPLOAD_URL = BASE_URL + "/mydrive/initupload";
        // URL to upload chunk of data
        public static string UPLOAD_APPEND_URL = BASE_URL + "/mydrive/appenddata";
        // URL to notify the webserver that upload is complete
        public static string UPLOAD_COMPLETE_URL = BASE_URL + "/mydrive/uploaddone";
        // URL to download chunk of data
        public static string DOWNLOAD_DATA_URL = BASE_URL + "/mydrive/download";

        // Data chunk size
        private static int CHUNK_SIZE = 50 * 1024;

        // Dictionary to hold all the pending uploads/downloads
        Dictionary<string, FileTransfer> pendingTransferList = new Dictionary<string, FileTransfer>();

        // Used to exit the worker thred
        bool thread_running_ = true;
        // Event used to notify the worker thread
        private AutoResetEvent newTransferEvent = new AutoResetEvent(false);
        public MainWindow()
        {
            InitializeComponent();
            // Get all the files hosted in the server
            Task.Run(() => GetAllFileList());
            // Start a background worker thread to handle all file transfers
            Thread newThread = new Thread(backgroundWorker_ProcessTransfers);
            newThread.Start();
        }

        /* Background worker thread to handle all uploads/download
        *  If there is nothing to transfer, it waits without consuming CPU
        */ 
        private void backgroundWorker_ProcessTransfers(object data)
        {
            // Restart any pending transfers, this can happen if your application has exited or crashed
            LoadTransferList();

            while (thread_running_)
            {
                newTransferEvent.WaitOne(5000);
                // Loop until all your transfers are complete
                while (pendingTransferList.Count > 0)
                {
                    try
                    {
                        bool server_connection_error = false;
                        foreach (KeyValuePair<string, FileTransfer> entry in pendingTransferList)
                        {
                            TransferStatus status = TransferStatus.INVALID_ERROR;
                            FileTransfer transferobj = entry.Value;
                            // Transfer is an upload
                            if (transferobj.transfer_type == TransferType.Upload)
                            {
                                status = UploadFileChunk(transferobj.file_id);
                                if (status == TransferStatus.FILE_TRANSFER_COMPLETE)
                                {
                                    // File transfer complete. remove item from the list and start 
                                    // a new enumeration
                                    RemoveItemFromPendingTransferList(transferobj.file_id);
                                    // Refresh the main file list
                                    Task.Run(() => GetAllFileList());
                                    break;
                                }
                            }
                            // Transfer is a download
                            else if (transferobj.transfer_type == TransferType.Download)
                            {
                                status = DownloadFileChunk(transferobj.file_id);
                                if (status == TransferStatus.FILE_TRANSFER_COMPLETE)
                                {
                                    // Download chunk complete remove from the list
                                    RemoveItemFromPendingTransferList(transferobj.file_id);
                                    break;
                                }
                            }

                            // Check if server is down, id so stop all pending transaction
                            if (status == TransferStatus.SEVRER_NOTREACHABLE)
                            {
                                transferobj.TransferMessage = "Paused";
                                server_connection_error = true;
                                break;
                            }
                        }
                        // Stop any pending transaction and wait for some time for server to be up
                        if (server_connection_error == true)
                        {
                            server_connection_error = false;
                            break;
                        }
                    }
                    catch(InvalidOperationException) { }
                }
            }
        }

        /* Add the transfer object to the dictionary
         */ 
        private void AddItemToPendingTransferList(string file_id, FileTransfer item)
        {
            pendingTransferList.Add(file_id, item);
            // Add transcation to transfer list view
            this.Dispatcher.BeginInvoke(new Action(() =>
                            transferListView.Items.Add(item)));
        }

        /* Remove transfer object from the dictionary
         */
        private void RemoveItemFromPendingTransferList(string file_id)
        {
            pendingTransferList.Remove(file_id);
            SerializeTransferList();
            this.Dispatcher.BeginInvoke(new Action(() => RemoveItemFromTransferListView(file_id)));
        }

        /* Remove list view item from UI
         */
        private void RemoveItemFromTransferListView(string file_id)
        {
            foreach (FileTransfer item in transferListView.Items)
            {
                if (item.file_id == file_id)
                {
                    transferListView.Items.Remove(item);
                    break;
                }
            }
        }

        /* Get the list view item for a particular transaction
         */
        private FileTransfer GetItemFromTransferListView(string file_id)
        {
            foreach (FileTransfer item in transferListView.Items)
            {
                if (item.file_id == file_id)
                {
                    return item;
                }
            }
            return null;
        }

        /* Update the transaction progress bar
         */
        private void UpdateTransferProgress(string file_id, int percent)
        {
            this.Dispatcher.BeginInvoke(new Action(() =>
            {
                FileTransfer item = GetItemFromTransferListView(file_id);
                if (item != null)
                {
                    item.TransferProgress = percent;
                    item.TransferMessage = "" + percent + "% completed"; 
                }
            }));
        }

        /* Rest api call to get the file information of an existing upload/download
         * This is used when restarting a file transfer after client termination
         */
        private long GetPendingFileSizeFromServer(string file_id)
        {
            var json_data = "";
            string url = String.Format("{0}/{1}", GET_PENDING_FILEINFO_URL, Uri.EscapeDataString(file_id));
            HttpWebRequest request = (HttpWebRequest)WebRequest.Create(url);
            using (HttpWebResponse response = (HttpWebResponse)request.GetResponse())
            using (Stream stream = response.GetResponseStream())
            using (StreamReader reader = new StreamReader(stream))
            {
                json_data = reader.ReadToEnd();
                var fileinfo = JsonConvert.DeserializeObject<ServerFileInfo>(json_data);
                // Get the downloaded data size
                if(fileinfo.error == "success")
                    return fileinfo.file_size;
            }
            return 0;
        }

        /* Invoked by the worker thread to reload all pending transaction after a client restart
         */
        private void LoadTransferList()
        {
            try
            {
                // load the data from the file
                string json_data = System.IO.File.ReadAllText(@"pending_list.json");
                var pendinglist = JsonConvert.DeserializeObject<Dictionary<string, FileTransfer>>(json_data);
                foreach (KeyValuePair<string, FileTransfer> entry in pendinglist)
                {
                    // If we are uploading, check total bytes server has received and proceed from there.
                    if (entry.Value.transfer_type == TransferType.Upload)
                    {
                        long file_size = GetPendingFileSizeFromServer(entry.Key);
                        // overiride the client data with server data
                        entry.Value.bytes_transfered = file_size;
                    }
                    AddItemToPendingTransferList(entry.Key, entry.Value);
                }
            }
            catch { }
        }

        /* Will save the pending transaction list to a file. This is used to reload the transaction
         * details if the client crashes
         */ 
        private void SerializeTransferList()
        {
            string json_data = JsonConvert.SerializeObject(pendingTransferList);
            System.IO.File.WriteAllText(@"pending_list.json", json_data);
        }

        /* Rest API to load server hosted files. 
         */ 
        private void GetAllFileList()
        {
            var json_data = "";
            HttpWebRequest request = (HttpWebRequest)WebRequest.Create(GET_FILE_LIST_URL);
            using (HttpWebResponse response = (HttpWebResponse)request.GetResponse())
            using (Stream stream = response.GetResponseStream())
            using (StreamReader reader = new StreamReader(stream))
            {
                // Clear the list view
                this.Dispatcher.BeginInvoke(new Action(() =>
                        fileListView.Items.Clear()));
                json_data = reader.ReadToEnd();
                // Parse the json from server
                var filelist = JsonConvert.DeserializeObject<List<ServerFileInfo>>(json_data);
                foreach (ServerFileInfo item in filelist)
                {
                    // Populate the data to list view
                    this.Dispatcher.BeginInvoke(new Action(() =>
                        fileListView.Items.Add(item)));
                }
            }

        }

        /* REST API to post binary data to webserver
         */ 
        private TransferStatus UploadChunkToServer(string file_id, byte[] data, int length)
        {
            try
            {
                string url = String.Format("{0}/{1}", UPLOAD_APPEND_URL, Uri.EscapeDataString(file_id));
                HttpWebRequest request = (HttpWebRequest)WebRequest.Create(url);
                request.ContentType = "multipart/form-data;";
                request.Method = "POST";
                Stream requeststream = request.GetRequestStream();
                requeststream.Write(data, 0, length);
                requeststream.Close();
                using (HttpWebResponse response = (HttpWebResponse)request.GetResponse())
                using (Stream stream = response.GetResponseStream())
                using (StreamReader reader = new StreamReader(stream))
                {
                    // read the response from server
                    string json_data = reader.ReadToEnd();
                    WebResult result = JsonConvert.DeserializeObject<WebResult>(json_data);
                    if (result.error == "success")
                    {
                        return TransferStatus.CHUNK_TRANSFER_SUCCESS;
                    }
                    else if(result.error == "file id is invalid")
                    {
                        return TransferStatus.FILE_ID_NOT_EXIST;
                    }
                }
            }
            catch (Exception)
            { }
            return TransferStatus.SEVRER_NOTREACHABLE;
        }

        /* This function reads data from the file and send it to webserver
         */
        private TransferStatus UploadFileChunk(string file_id)
        {
            try
            {
                FileTransfer transferobj = pendingTransferList[file_id];
                // Open local file
                using (var inFileSteam = new FileStream(transferobj.file_localpath, FileMode.Open))
                {
                    inFileSteam.Seek(transferobj.bytes_transfered, SeekOrigin.Begin);
                    byte[] buffer = new byte[CHUNK_SIZE]; // 50KB chunk
                    int bytesRead = inFileSteam.Read(buffer, 0, buffer.Length);

                    // Send data to webserver
                    TransferStatus status = UploadChunkToServer(file_id, buffer, bytesRead);
                    if (status == TransferStatus.CHUNK_TRANSFER_SUCCESS)
                    {
                        // Upload chunk is success update the progress bar
                        transferobj.bytes_transfered += bytesRead;
                        UpdateTransferProgress(file_id, (int)((double)((double)transferobj.bytes_transfered / (double)transferobj.total_size) * 100));
                        SerializeTransferList();
                        // Check if we have completed the transfer
                        if (transferobj.bytes_transfered >= transferobj.total_size)
                        {
                            if(EndUpload(file_id) == 0)
                            {
                                return TransferStatus.FILE_TRANSFER_COMPLETE;
                            }
                        }
                        return TransferStatus.CHUNK_TRANSFER_SUCCESS;
                    }
                    else if( status == TransferStatus.FILE_ID_NOT_EXIST)
                    {
                        // Server does not have valid id. It mean transaction is complete, we need to clear our dictionary
                        return TransferStatus.FILE_TRANSFER_COMPLETE;
                    }
                    
                }
            }
            catch (Exception)
            { }
            return TransferStatus.SEVRER_NOTREACHABLE;
        }

        /* REST API to inform webserver that upload is complete.
         */ 
        private int EndUpload(string file_id)
        {
            string url = String.Format("{0}/{1}", UPLOAD_COMPLETE_URL, Uri.EscapeDataString(file_id));
            HttpWebRequest request = (HttpWebRequest)WebRequest.Create(url);
            using (HttpWebResponse response = (HttpWebResponse)request.GetResponse())
            using (Stream stream = response.GetResponseStream())
            using (StreamReader reader = new StreamReader(stream))
            {
                string json_data = reader.ReadToEnd();
                WebResult result = JsonConvert.DeserializeObject<WebResult>(json_data);
                if (result.error == "success")
                {
                    return 0;
                }
            }
            return -1;
        }

        /* REST API to initiate a upload. 
         */ 
        private void InitUpload(string localfilepath)
        {
            // Inform the webserver about the upload
            string fname = System.IO.Path.GetFileName(localfilepath);
            string url = String.Format("{0}/{1}", INIT_UPLOAD_URL, Uri.EscapeDataString(fname));
            HttpWebRequest request = (HttpWebRequest)WebRequest.Create(url);
            using (HttpWebResponse response = (HttpWebResponse)request.GetResponse())
            using (Stream stream = response.GetResponseStream())
            using (StreamReader reader = new StreamReader(stream))
            {
                string json_data = reader.ReadToEnd();
                FileTransfer transferobj = JsonConvert.DeserializeObject<FileTransfer>(json_data);
                // Server will generate the file_id, check if it is null
                if (string.IsNullOrEmpty(transferobj.file_id) == false)
                {
                    // Assign the default value for transfer object
                    transferobj.TransferProgress = 0;
                    transferobj.file_localpath = localfilepath;
                    transferobj.total_size = new System.IO.FileInfo(localfilepath).Length;
                    transferobj.transfer_type = TransferType.Upload;
                    transferobj.TransferMessage = "Uploading";
                    // Add the item to transfer list and UI
                    AddItemToPendingTransferList(transferobj.file_id, transferobj);
               }
            }
        }

        /* Upload button UI click handler
         */
        private void uploadButton_Click(object sender, RoutedEventArgs e)
        {
            OpenFileDialog openFileDialog = new OpenFileDialog();
            openFileDialog.InitialDirectory = Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments);
            if (openFileDialog.ShowDialog() == true)
            {
                // Async task to initiate the upload
                Task.Run(() => InitUpload(openFileDialog.FileName));
            }

        }

        /* REST API to get data from webserver
         */
        private TransferStatus DownloadDataFromServer(string file_id, ref byte[] data, long offset, int bytes_to_read, ref int bytes_read)
        {
            try
            {
                string url = String.Format("{0}/{1}/{2}/{3}", DOWNLOAD_DATA_URL, Uri.EscapeDataString(file_id), offset, bytes_to_read);
                HttpWebRequest request = (HttpWebRequest)WebRequest.Create(url);
                using (HttpWebResponse response = (HttpWebResponse)request.GetResponse())
                using (Stream stream = response.GetResponseStream())
                {
                    int count = 0;
                    // Need to read data in a loop as we might get partial block
                    do
                    {
                        count = stream.Read(data, bytes_read, (bytes_to_read - bytes_read));
                        if (count > 0)
                            bytes_read += count;
                        // if count == 0 means no more data to read
                        else if (count == 0)
                            return TransferStatus.CHUNK_TRANSFER_SUCCESS;

                    } while (bytes_read < bytes_to_read);
                    return TransferStatus.CHUNK_TRANSFER_SUCCESS;
                }
            }
            catch (Exception)
            { }
            return TransferStatus.SEVRER_NOTREACHABLE;
        }

        /* This function get chunk from webserver and write it to file
         */
        private TransferStatus DownloadFileChunk(string file_id)
        {
            try
            {
                FileTransfer transferobj = pendingTransferList[file_id];
                byte[] buffer = new byte[CHUNK_SIZE]; // 50KB
                int bytesToRead = CHUNK_SIZE;
                int bytesRead = 0;
                // Get the data from webserver
                TransferStatus status = DownloadDataFromServer(file_id, ref buffer, transferobj.bytes_transfered, bytesToRead, ref bytesRead);
                if (status == TransferStatus.CHUNK_TRANSFER_SUCCESS)
                {
                    transferobj.bytes_transfered += bytesRead;
                    if (bytesRead > 0)
                    {
                        // We received data, write the chunk to file
                        using (var outFileSteam = new FileStream(transferobj.file_localpath, FileMode.Append))
                        {
                            outFileSteam.Write(buffer, 0, bytesRead);
                        }
                    }
                    // Update the progress bar
                    UpdateTransferProgress(file_id, (int)((double)((double)transferobj.bytes_transfered / (double)transferobj.total_size) * 100));
                    SerializeTransferList();
                    if (transferobj.bytes_transfered >= transferobj.total_size)
                    {
                        // file download is complete
                        return TransferStatus.FILE_TRANSFER_COMPLETE;
                    }

                    return TransferStatus.CHUNK_TRANSFER_SUCCESS;
                }
                else if(status == TransferStatus.SEVRER_NOTREACHABLE)
                {
                    return TransferStatus.SEVRER_NOTREACHABLE;
                }
            }
            catch (Exception)
            { }
            return TransferStatus.SEVRER_NOTREACHABLE;
        }

        /* This function initiate the download of a file
         */ 
        private void InitiateDownloadFile(string file_id, string file_name, long file_size)
        {
            // Create file transfer object and assign default values
            FileTransfer transferobj = new FileTransfer();
            transferobj.file_id = file_id;
            transferobj.total_size = file_size;
            transferobj.bytes_transfered = 0;
            transferobj.TransferProgress = 0;
            // Create the "my drive" folder to store all downloaded filess
            string local_folder = System.IO.Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments), "MyDrive");
            System.IO.Directory.CreateDirectory(local_folder);
            transferobj.file_localpath = System.IO.Path.Combine(local_folder, file_name);
            transferobj.transfer_type = TransferType.Download;
            transferobj.TransferMessage = "Downloading";
            // Add the transaction to pending list for backgroung thread to process
            AddItemToPendingTransferList(transferobj.file_id, transferobj);
        }

        /* Download context menu handler
         */ 
        private void DownloadContextMenu_OnClick(object sender, RoutedEventArgs e)
        {
            if (fileListView.SelectedIndex > -1)
            {
                ServerFileInfo serverFileInfo = new ServerFileInfo();
                serverFileInfo = (ServerFileInfo)fileListView.SelectedItem; // casting the list view 
                InitiateDownloadFile(serverFileInfo.file_id, serverFileInfo.file_name, serverFileInfo.file_size);
            }
        }
   }
}
